### ISSUE TITLE
ENABLE_LEGACY mismatch using cmake

### ISSUE THREAD

**Issue by gitterdude** [dbry/WavPack#128]
When I run cmake on commit 36b08db without any options it says
_-- The following features have been disabled:
  ENABLE_LEGACY, Decode legacy (< 4.0) WavPack files._

 Adding -DENABLE_LEGACY=1 shows
_CMake Warning:
  Manually-specified variables were not used by the project:
    ENABLE_LEGACY_

The proper way appears to be adding -DWAVPACK_ENABLE_LEGACY=1 , so it should be reflected in the first message

**Comment by dbry** [comment]
Hi. I am unfortunately not very familiar with `cmake`, but I found the command `cmake -LH` and it displayed this, which seems to be the right thing:
```
// Decode legacy (< 4.0) WavPack files
WAVPACK_ENABLE_LEGACY:BOOL=OFF
```
I looked at the `CMakeLists.txt` file and it used both `WAVPACK_ENABLE_LEGACY` and `ENABLE_LEGACY` as different things so I don't really know how I would fix this.

Any comments @evpobr ?

Thanks!

**Comment by evpobr** [comment]
@gitterdude , this happened due to different feature names and options. Generally speaking, this is not an error, they do not have to match and the message does not say to use the `ENABLE_LEGACY` option anywhere.

@dbry , in general, there is no problem to make the names of features and options match, why not. I will make PR.

**Comment by evpobr** [comment]
Ready, #129 .
