### ISSUE TITLE
Channels in CAF file that have no corresponding in Microsoft definition

### ISSUE THREAD

**Issue by nu774** [dbry/WavPack#15]
First, thanks for supporting channel layouts with non-MS order in a clean and compatible way.

This issue is about mapping of channels that have no corresponding in WAV (such as rear left surround/rear right surround).

As far as I can see, you are following Apple's ChannelLabel constants definition, where some of surround channels are mapped like following:

  Lsd/Rsd -> SL/SR
  Ls/Rs -> BL/BR
  Rls/Rrs -> (no corresponding channels in wav)
  Lw/Rw -> (no corresponding channels in wav)

And currently, no bits are assigned (in channel mask)  for Rls/Rrs and Lw/Rw.
Although it is understandable, I'm somewhat uncomfortable on it (because, information about those channels are effectively lost from application point of view).

And also, I don't think those mappings of surround channels are appropriate.
Let's look at what ffmpeg does (libavutil/channel_layout.h and libavformat/mov_chan.c):

1. Ls/Rs are mapped to SL/SR, not BL/BR
2. Rls/Rrs are mapped to BL/BR
3. Higher bits of 64bit mask (beyond MS definition) are used for those channels that have no corresponding in MS definition (Lw/Rw or something, and also Lsd/Rsd)

Looking at actual usage of Ls/Rs, Rls/Rrs, and Lsd/Rsd, I think ffmpeg mapping is more appropriate because:

1. Ls/Rs are used for 5.1 system. According to recent Dolby recommendation of speaker layout, they are placed on the side.

1. Rls/Rrs are used for 7.1 system, and they are added to the rear. And because of this, I think 5.1ch side (FL FR FC LF SL SR) is more common these days than 5.1ch back (FL FR FC LF BL BR)

1. Use of Lsd/Rsd is rare compared to Ls/Rs and Rls/Rrs. Therefore, Ls/Rs and Rls/Rrs should have higher priority than Lsd/Rsd and should have normal mapping to WAV channels.

Using 64bit mask might be questionable, though. Looking at channel_layout.h, number of channels defined by ffmpeg is less than 31, therefore should still fit into 32bit mask.
Hope you can think of some clean solution.

**Comment by dbry** [comment]
There seem to be two issues being reported here. The first is that the channel assignments in Apple's CAF document are perhaps not the best (and you are correct, that is where I got the assignments). At first I thought that I should probably follow the CAF spec, but I see that it is 10 years old and I am certainly not an expert in this. If you think I should change the channel layouts in the way you suggest, then I will do that. Would you like to provide a patch, or should I try to figure it out and have you check it?

The other issue is what to do for channel layouts that have non-Microsoft channels. I believe that some of these will be fixed with the changes above (the ones with Rls and Rrs, for example), however this will still leave a few layouts with unassigned channel mappings. I'm not sure what you mean about the information about those channels being effectively lost.

Obviously that information is lost with respect to WAVFORMATEXTENSIBLE because Microsoft has reserved the other bits and nobody would understand if any were set, but all of the information available in the CAF file (the layout ID [100-146] and re-ordering done before encoding) is available to the application through the WavpackGetChannelLayout() function. That is what wvunpack uses to duplicate the exact layout in the source file. Unless you are talking about any information stored in the channel configuration array, there is no more information to pass to the application.

Are you just referring to passing the same information back to the app in a non-CAF-centric way? What am I missing?

**Comment by nu774** [comment]
Well actually, wvunpack with explicit --caf-le doesn't seem to restore the original CAF channel layout  (seems like WavpackGetChannelLayout() returning zero, and resulting chan chunk is filled with zero). Am I missing something?
Also I noticed that inside of pack.c/pack_samples(), a call to free_metadata() triggers a runtime error on Visual Studio debugger due to heap corruption.

**Comment by nu774** [comment]
> but all of the information available in the CAF file (the layout ID [100-146] and re-ordering done before encoding) is available to the application through the WavpackGetChannelLayout() function.

Well, if I understand correctly, only mChannelLayoutTag is stored. Therefore, when mChannelLayoutTag was kAudioChannelLayoutTag_UseChannelDescriptions, I'm afraid 'chan' chunk cannot be exactly restored.
Moreover, if description array contains channels larger than 18 or it's not ordered ascending, it cannot be exactly mapped into channel mask and it's information is lost.

**Comment by dbry** [comment]
Yes, you are correct that only the layout tag is stored. If the tag is one of the defined layouts (including **_UseChannelBitmap) then no channel information is lost.

If the layout tag is **_UseChannelDescriptions then some information may be lost, depending on what information is present in the descriptions array. I am not going to try to store the flags and coordinates if those are present, however if only the channelLabels are used then I attempt to provide something useful. I believe that there are 5 possible scenarios:

1. All channel labels are in MS range (1-18) and present in the MS order
2. All channel labels are in MS range (1-18), but NOT in MS order
3. Some channel labels are in MS range, and those are first and in MS order
4. Some channels labels are in MS range, but NOT first and/or NOT in MS order
5. No channel labels are in MS range

Currently I handle case #1 and no information is lost. Also, case #3 is handled except that the application must parse the CAF header to determine the identity of the non-MS channels, but when unpacking to WAV all the information applicable to that format is exported. Case #5 will not be supported (channel order will be unchanged and application must parse CAF header to find out what's there).

I believe that I can add full support for case #2, but it's a little complicated. The channels will be reordered to MS order, and that re-ordering will be available to the unpacker for creating verbatim CAF files (i.e., with original header). However, what do I do when the user requests a new CAF header on unpacking? Do I leave the channels in MS order and set **_UseChannelBitmap or do I regenerate the channel description array? I am leaning toward the latter because in that case the MD5 checksum will be valid, but it's kind of a waste because really no new information is being provided by the array.

That only leave case #4. Currently I only set bits in the bitmap as long as they are in MS range and in ascending order...as soon as a non-MS or wrong-order channel occurs, I stop. I don't particularly like this because it's not ideal for exporting to WAV (some MS channels are lost). I could reorder the channels so that the MS channels are first and in the right order, and set the channel bitmap, and provide the reordering information for the unpacker. That would be better for WAV export, but more complicated for an application that wanted to parse the CAF header (because of the reordering) and all kinds of issues with exporting to new CAF files (do I generate description arrays with “unknown” channels). I think I'll leave this one alone for now.

**Comment by dbry** [comment]
I have added the ability to store non-Microsoft channel identities in WavPack files. Currently, this information can only come from or be exported to CAF files, but APIs are there for other applications to use.

I will add this to the Audition Amio plugins because they can handle non-Microsoft channels, and at that time I will also reserve more of the available 8-bit channel codes (currently I just reserved the ones required for Core Audio). The only Core Audio spec not handled now is channels that are defined by position coordinates alone.

Thanks again for pushing me on this!
