### ISSUE TITLE
Heap corruption?

### ISSUE THREAD

**Issue by nu774** [dbry/WavPack#16]
When running wavpack.exe from Visual Studio IDE debugger, an error dialog is shown due to "HEAP CORRUPTION DETECTED" inside free_metadata() called from pack_samples().

**Comment by dbry** [comment]
Thanks for letting me know about this! I looked over the code and could not seen anything obvious. Does this happen with any particular source file, or with every file? There are many calls to free_metadata() inside pack_samples()...is the debugger telling you which one fails?

**Comment by lvqcl** [comment]
inside add_to_metadata():
```
    mdp->data = realloc (mdp->data, mdp->byte_length + bc);
    ...
    mdp->byte_length += bc;
```
here mdp->byte_length==0, bc==3; so 'data' size is 3

then in copy_metadata():
```
    if (wpmd->byte_length & 1)
        ((char *) wpmd->data) [wpmd->byte_length] = 0;
```
here wpmd->byte_length is 3 so it looks like this code writes 1 byte past the buffer.

**Comment by dbry** [comment]
Ah, okay. It's funny because I already found that at one point and fixed it write_metadata() and left the commented line in there, but didn't notice it in copy_metadata(). The byte will also be read, so I need to fix that too (and a debug malloc() probably would not have caught just a read).

Thanks to both of you!

**Comment by dbry** [comment]
Fixed in master.
