### ISSUE TITLE
SIGILL: Illegal instruction  in entropy_utils.c:169,  wp_exp2s()

### ISSUE THREAD

**Issue by schsiung** [dbry/WavPack#175]
## Expected behavior and actual behavior.

[SIGILL_POC_wavpack.tar.gz](https://github.com/dbry/WavPack/files/13946989/SIGILL_POC_wavpack.tar.gz)

Expect running without SIGILL .

## Steps to reproduce the problem.
1. ` fuzzer output2/default/crashes/id:000000,sig:04,src:000067,time:42903,execs:43922,op:havoc,rep:9`  
```
 [AFL++ 4547ba12d0d6] /data/openeuler/wavpack/wavpack/fuzzing # /data/openeuler/wavpack/wavpack/fuzzing/fuzzer /data/openeuler/wavpack/wavpack/fuzzing/output2/default/crashes/id:000000,sig:04,src:000067,time:42903,execs:43922,op:havoc,rep:9
read 1000 bytes from file /data/openeuler/wavpack/wavpack/fuzzing/output2/default/crashes/id:000000,sig:04,src:000067,time:42903,execs:43922,op:havoc,rep:9
warning: at maximum length, perhaps truncated!
Illegal instruction
[AFL++ 4547ba12d0d6] /data/openeuler/wavpack/wavpack/fuzzing # 
```

2.  LLDB info  `lldb fuzzing/fuzzer` 

run fuzzing/output2/default/crashes/id:000000,sig:04,src:000067,time:42903,execs:43922,op:havoc,rep:9
```
(lldb) target create "/data/openeuler/wavpack/wavpack/fuzzing/fuzzer"
Current executable set to '/data/openeuler/wavpack/wavpack/fuzzing/fuzzer' (x86_64).
(lldb) run  /data/openeuler/wavpack/wavpack/fuzzing/output2/default/crashes/id:000000,sig:04,src:000067,time:42903,execs:43922,op:havoc,rep:9
Process 2895276 launched: '/data/openeuler/wavpack/wavpack/fuzzing/fuzzer' (x86_64)
read 1000 bytes from file /data/openeuler/wavpack/wavpack/fuzzing/output2/default/crashes/id:000000,sig:04,src:000067,time:42903,execs:43922,op:havoc,rep:9
warning: at maximum length, perhaps truncated!
Process 2895276 stopped
* thread #1, name = 'fuzzer', stop reason = signal SIGILL: illegal instruction operand
    frame #0: 0x000055555569d733 fuzzer`wp_exp2s(log=<unavailable>) at entropy_utils.c:0
   335  // but since a full 32-bit value is returned this can be used for unsigned
   336  // conversions as well (i.e. the input range is -8192 to +8447).
   337 
-> 338  int32_t wp_exp2s (int log)
   339  {
   340      uint32_t value;
   341 
Note: this address is compiler-generated code in function wp_exp2s that has no source code associated with it.
(lldb) p log
error: Couldn't materialize: couldn't get the value of variable log: Could not evaluate DW_OP_entry_value.
error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression
(lldb) bt
* thread #1, name = 'fuzzer', stop reason = signal SIGILL: illegal instruction operand
  * frame #0: 0x000055555569d733 fuzzer`wp_exp2s(log=<unavailable>) at entropy_utils.c:0
    frame #1: 0x000055555569df07 fuzzer`read_hybrid_profile(wps=0x000061d000000080, wpmd=<unavailable>) at entropy_utils.c:169:36
    frame #2: 0x000055555568cb82 fuzzer`unpack_init(wpc=0x0000617000000080, stream=<unavailable>) at open_utils.c:342:14
    frame #3: 0x0000555555683a8c fuzzer`WavpackOpenFileInputEx64(reader=<unavailable>, wv_id=<unavailable>, wvc_id=<unavailable>, error=<unavailable>, flags=<unavailable>, norm_offset=<unavailable>) at open_utils.c:175:33
    frame #4: 0x0000555555676233 fuzzer`::LLVMFuzzerTestOneInput(data="wvpk\x9c\U00000003", size=1000) at fuzzer.cc:147:11
    frame #5: 0x00005555556773f8 fuzzer`main(argc=2, argv=0x00007fffffffe208) at fuzzer.cc:296:9
    frame #6: 0x00007ffff7a7cd90 libc.so.6`__libc_start_call_main(main=(fuzzer`main at fuzzer.cc:273), argc=2, argv=0x00007fffffffe208) at libc_start_call_main.h:58:16
    frame #7: 0x00007ffff7a7ce40 libc.so.6`__libc_start_main_impl(main=(fuzzer`main at fuzzer.cc:273), argc=2, argv=0x00007fffffffe208, init=0x00007ffff7ffd040, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffe1f8) at libc-start.c:392:3
    frame #8: 0x00005555555af565 fuzzer`_start + 37
(lldb) 
```

 
## Operating system

```
[AFL++ 4547ba12d0d6] /data/openeuler/wavpack/wavpack/fuzzing # uname -a
Linux 4547ba12d0d6 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[AFL++ 4547ba12d0d6] /data/openeuler/wavpack/wavpack/fuzzing # cc --version
cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[AFL++ 4547ba12d0d6] /data/openeuler/wavpack/wavpack/fuzzing # git log
commit b28fdab79dd8af2b8281d77097cf8f25e580e525 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: 2ji3150 <2ji3150@gmail.com>
Date:   Mon Jan 1 09:06:04 2024 +0900

    Update dates in license to 2024
[AFL++ 4547ba12d0d6] /data/openeuler/wavpack/wavpack/fuzzing # 
```

##  version

wavpack latest - with commit id b28fdab79dd8af2b8281d77097cf8f25e580e525

From: 
[xiongshengchao@jyhlab.org.cn](mailto:xiongshengchao@jyhlab.org.cn)

**Comment by dbry** [comment]
Thanks for taking the time to report this issue!

You are almost correct in your diagnosis. The problem not on line 169:

https://github.com/dbry/WavPack/blob/b28fdab79dd8af2b8281d77097cf8f25e580e525/src/entropy_utils.c#L169

In this case the value 32768 is being cast to an int16_t into which it does not fit. However, according to C specification this is simply _implementation-dependent_, not _undefined-behavior_. So the result might vary between implementations, but since this is an invalid WavPack file created by fuzzing, any difference would be inconsequential.

The actual problem comes later on line 343:

https://github.com/dbry/WavPack/blob/b28fdab79dd8af2b8281d77097cf8f25e580e525/src/entropy_utils.c#L343

Here we are negating -2147483648 which cannot be represented by an int (the result is -2147483648 which is obviously not its own negation). This is _undefined behavior_, and is fixed by casting to an unsigned before the negation, which I will implement.

Fortunately I don’t believe there are any security implications because this could only trigger when running with a sanitizer (i.e., no buffer overflows could be caused by this; it’s purely arithmetic downstream and the error would be caught eventually by checksums).

Thanks again and please let me know if you find anything else!

**Comment by dbry** [comment]
BTW, I really don't understand why this generated an illegal instruction. If this was being run with undefined behavior sanitizer then it should have been simply caught with that (that's how I found it). This sounds like there might be a bug in your fuzzing environment.

Interestingly I once ran into illegal instructions during fuzz testing myself, and it ended up being caused by using an older processor. See my comment here:

https://github.com/google/fuzzing/issues/26#issuecomment-761746849

Finally, it would have been nice to have the file that actually triggered the error to make sure I was fixing the right thing (I could not find it in the attachment). I was able to create a test file that seem to have the same error value, but I still can't be sure I caught everything.

Thanks!

**Comment by schsiung** [comment]
@dbry Thanks for  you replied, I have checked the assembly code and get:
```
Process 4119870 stopped
* thread #1, name = 'fuzzer', stop reason = breakpoint 2.1
    frame #0: 0x000055555569d733 fuzzer`wp_exp2s(log=<unavailable>) at entropy_utils.c:0
   335  // but since a full 32-bit value is returned this can be used for unsigned
   336  // conversions as well (i.e. the input range is -8192 to +8447).
   337 
-> 338  int32_t wp_exp2s (int log)
   339  {
   340      uint32_t value;
   341 
Note: this address is compiler-generated code in function wp_exp2s that has no source code associated with it.
(lldb) x/i 0x000055555569d733
->  0x55555569d733: 67 0f b9 40 0d  ud1l   0xd(%eax), %eax
```
The `ud1l   ` seems to be a wrong assembly instruction generated by `[UBSAN](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html)`
