### ISSUE TITLE
No DLL for 5.7.0?

### ISSUE THREAD

**Issue by b9AcE** [dbry/WavPack#179]
Considering how it has been for previous releases I expected to find next to the new release's "wavpack-5.7.0-x64.zip" also a "wavpack-5.7.0-dll.zip", but there does not seem to be any DLL in this release.
Is this intentional? Are we not supposed to update our "wavpackdll.dll" and "wavpackdll.lib" for this release?

**Comment by dbry** [comment]
No, it is not intentional. I simply have not gotten to creating and testing the DLL package yet, and this is complicated by possibly switching to `MinGW`. I plan to have this done in a day or two. And in fact it would have been impossible for applications using the DLL to use the new multithreading feature without a new DLL, so this definitely had to be done.

I'm actually glad to hear about this though because I wasn't sure that people were actually using the DLL package!

**Comment by b9AcE** [comment]
Aha. Thank you very much for the information!

**Comment by dbry** [comment]
I did end up running into trouble using the MinGW DLLs, so I have decided to stick with MSVC artifacts for now until I can get that sorted.

But in any event, the new DLLs are now available. Please let me know if you run into any issues. Thanks!
