### ISSUE TITLE
FLAC comparison

### ISSUE THREAD

**Issue by svnpenn** [dbry/WavPack#21]
This is almost certainly off topic, but as I currently use FLAC and I just learned that WavPack exists, it is really the only question that I care about. Does WavPack have any speed/size comparisons out there? I found this one:

http://fmedia.firmdev.com/audio-formats

which shows WavPack with slightly better compress, but getting destroyed in the decode time. Also it shows that WavPack cant even encode?

**Comment by dbry** [comment]
Well, WavPack definitely encodes. That comparison only shows encoding speeds for codecs that fmedia can encode itself. A good rule of thumb is that WavPack, Monkey's Audio (APE), and OptimFROG are all symmetrical, so they roughly encode and decode at the same rate (unlike FLAC, as you can see from the table). Here's another comparison of the major lossless compressors: 

[http://wiki.hydrogenaud.io/index.php?title=Lossless_comparison](url)

I would say that if FLAC does exactly what you want, then there's no reason to consider alternatives. It's a great format and certainly the most widely supported, and any differences in compression with other formats are going to very small.

People generally turn to WavPack because it has a lot of features that FLAC does not have. For example, it handles 32-bit data (integer and float), it handles DSD audio, and it also has lossy and hybrid modes (PCM only) that might be useful in some situations.

**Comment by ValZapod** [comment]
> it handles 32-bit data (integer and float)

Flac can also do 32 bit. At least one type of that.

**Comment by Artoria2e5** [comment]
Flac does int32 and recently DSD (with no guarantee of losslessness). Is WavPack lossless with DSD and float32?
