### ISSUE TITLE
CUE Spilit

### ISSUE THREAD

**Issue by 2ji3150** [dbry/WavPack#56]
When I use foobar2000 with cue+WavPack split ,
I found that it is just re-encode again and eat all of my cpu which is not expected.
Is this normal? Can Wavpack  be split without re-encode agian?

**Comment by dbry** [comment]
I think that's what's happening. It is _possible_ to split WavPack files without re-encoding, except that if the split point is not right on a WavPack frame boundary, then the partial blocks on either side need to be re-encoded. Obviously this is pretty complicated and I don't think anybody does that. Of course, if the files are lossless (pure or hybrid) then this is only an inconvenience. If lossy, then it's a more serious problem.

**Comment by dbry** [comment]
Unfortunately, no, the WavPack command-line program does not support cue splitting. I have thought about providing that and then it would be possible to split by cues _without_ re-encoding.

However, as it is _now_, there is no way to split a WavPack file without re-encoding. But if you have only lossless files then it takes a little while to re-encode, but you do not lose any data and the operation is safe. It is not really a foobar2000 issue, the problem is that the WavPack library does not provide this functionality and so the only way that foobar2000 can split is by re-encoding.
