### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Wetrain** [dbry/WavPack#63]
Hi,

There are a few CVEs open against this repository, which we are using as part of our distribution.

There are fixes that have been merged since the last release, such as: https://nvd.nist.gov/vuln/detail/CVE-2018-10536, to mitigate some CVEs.

When will the next release occur so we can update and mitigate from these vulnerabilities?

**Comment by dbry** [comment]
I have been working on some new features that I would like to add (like accepting AIFF files and ID3v2.2 tags), but have been very busy with paying work lately and so haven't had any time, and I am not sure when that will change.

However, I will try to produce a 5.1.1 bugifx release in the next month or so because there have been a lot of simple fixes and improvements since the last release that would be great to get in.

Thanks for bringing this up!

**Comment by Wetrain** [comment]
Hi @dbry,

understandable and thanks for the response, we will keep track of this release and upgrade when it is ready :)

**Comment by dbry** [comment]
[WavPack 5.2.0 Release](https://github.com/dbry/WavPack/releases/tag/5.2.0)

Sorry for the delay on this, and I should have mentioned this before, but I would like to say now that the reason that I was not overly concerned about a prompt release is that all of the outstanding CVEs only involve the use of the WavPack command-line program and malformed _source_ files (not malformed _WavPack_ files). There were absolutely no exploitable bugs in the library or the command-line decoder, and only one or two of the CVEs were actually possible to exploit, and again would have required manual execution by the user. In any event, there's a new release now with all the fixes in. Thanks!
