### ISSUE TITLE
Possible infinite loop in WavpackPackInit

### ISSUE THREAD

**Issue by hepoun** [dbry/WavPack#74]
When WavpackContext is configured for zero channels (although it isn't a viable usecase) the WavpackPackInit() ends in infinite loop. I suspect the following code:

https://github.com/dbry/WavPack/blob/22977b29c20f55fb27decfb9ad40d531599fa2b1/src/pack_utils.c#L519-L520

(v5.1.0)

**Comment by dbry** [comment]
Thanks for pointing this out. I was already made aware of this and decided to fix it in the individual parsers instead of in the library. You can see those fixes [here](https://github.com/dbry/WavPack/commit/cd353bccafb1274a525c3536aaff8c48c3a33aa0) and [here](https://github.com/dbry/WavPack/commit/4c0faba32fddbd0745cbfaf1e1aeb3da5d35b9fc) for example.

I agree that it should be checked for in the library and will do that before the next release, but I think it would be silly to backport this into previous versions because, unlike the _decoder_, the _encoder_ would never be the default handler for any file type.

Thanks again!

**Comment by dbry** [comment]
[Fixed here.](https://github.com/dbry/WavPack/commit/9e59b86416b4374126420fd4fe3d248b73b13983#diff-9d527aed6a650f3a67df84ca03cb953e)
